apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth-keycloak
  name: auth-keycloak
  namespace: egs-fuellink
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: auth-keycloak
