apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth-postgres
  name: auth-postgres
  namespace: egs-fuellink
spec:
  clusterIP: None
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    app: auth-postgres
