apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: auth-postgres
  name: auth-postgres
  namespace: egs-fuellink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-postgres
  serviceName: "auth-postgres"
  template:
    metadata:
      labels:
        io.kompose.network/auth-default: "true"
        app: auth-postgres
    spec:
      containers:
        - env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_DB
              value: keycloak
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: auth-postgres-secret
                  key: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-postgres-secret
                  key: password
          image: postgres:16-alpine
          name: auth-postgres
          ports:
            - containerPort: 5432
              hostPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: auth-postgres-claim0
      restartPolicy: Always
  volumeClaimTemplates:
    - metadata:
        name: auth-postgres-claim0
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
