apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: app
  name: app
  namespace: egs-fuellink
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/kafka-network: "true"
        io.kompose.service: app
    spec:
      containers:
        - env:
            - name: PORT
          image: app
          name: nest-docker-postgres
          ports:
            - containerPort: 4200
              hostPort: 4200
              protocol: TCP
          volumeMounts:
            - mountPath: /app/src
              name: app-cm0
          resources: {}
      restartPolicy: Always
      volumes:
        - configMap:
            name: app-cm0
          name: app-cm0
