apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    io.kompose.service: db
  name: db
  namespace: egs-fuellink
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db
  serviceName: "auth-postgres"
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/kafka-network: "true"
        io.kompose.service: db
    spec:
      containers:
        - env:
            - name: POSTGRES_PASSWORD
              value: postgres
          image: postgres
          name: postgres
          ports:
            - containerPort: 5432
              hostPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-claim0
      restartPolicy: Always
  volumeClaimTemplates:
  - metadata:
      name: db-claim0
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
