apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: composer-angular
  name: composer-angular
  namespace: egs-fuellink
spec:
  ports:
    - name: "4200"
      port: 4200
      targetPort: 4200
  selector:
    io.kompose.service: composer-angular
