apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: composer-influxdb
  name: composer-influxdb
  namespace: egs-fuellink
spec:
  clusterIP: None
  ports:
    - name: "8086"
      port: 8086
      targetPort: 8086
  selector:
    io.kompose.service: composer-influxdb
